@startuml

entity "User" {
    * id : UUID <<PK>>
    --
    * first_name : varchar(100)
    * last_name : varchar(100)
    * password : varchar(50)
    * created_at : timestamp
    * updated_at : timestamp
}

entity "DeviceType" {
    * id : UUID <<PK>>
    --
    * name : varchar(50)
    * description : varchar(100)
    * created_at : timestamp
    * updated_at : timestamp
}

entity "House" {
    * id : UUID <<PK>>
    * user_id : UUID <<FK>>
    --
    * name : varchar(50)
    * address : varchar(100)
    * description : varchar(100)
    * created_at : timestamp
    * updated_at : timestamp
}

entity "HouseRoom" {
    * id : UUID <<PK>>
    * house_id : UUID <<FK>>
    --
    * name : varchar(50)
    * description : varchar(100)
    * created_at : timestamp
    * updated_at : timestamp
}

entity "Device" {
    * id : UUID <<PK>>
    * user_id : UUID <<FK>>
    * device_type_id : UUID <<FK>>
    * house_room_id : UUID <<FK>>
    --
    * name : varchar(100)
    * model : varchar(100)
    * status_connect : varchar(20)
    * value : json
    * is_enabled : boolean
    * ip_address : varchar(20)
    * created_at : timestamp
    * updated_at : timestamp
}

entity "DeviceMetrics" {
    * id : UUID <<PK>>
    * device_id : UUID <<FK>>
    --
    * name : varchar(100)
    * data : json
    * created_at : timestamp
}

entity "ActionAutomatic" {
    * id : UUID <<PK>>
    * user_id : UUID <<FK>>
    --
    * name : varchar(50)
    * description : varchar(100)
    * is_enabled : boolean
    * created_at : timestamp
    * updated_at : timestamp
}

entity "ActionAutomaticCapability" {
    * id : UUID <<PK>>
    * action_automatic_id : UUID <<FK>>
    * device_id : UUID <<FK>>
    --
    * capability_type : varchar(50)
    * command : varchar(100)
    * data : json
    * created_at : timestamp
    * updated_at : timestamp
}

User ||--o{ Device
DeviceType ||--o{ Device
Device ||--o{ DeviceMetrics

House ||--o{ HouseRoom
HouseRoom ||--o{ Device

Device ||--o{ ActionAutomaticCapability
ActionAutomatic ||--o{ ActionAutomaticCapability

User ||--o{ ActionAutomatic
User ||--o{ House

@enduml